[rpc]
address = "http://localhost:26657"

[grpc]
address = "localhost:9090"

[lcd]
address = "http://localhost:1317"

[custom]
mnemonics = ["guard cream sadness conduct invite crumble clock pudding hole grit liar hotel maid produce squeeze return argue turtle know drive eight casino maze host"]

gas_limit = 100000000
fee_denom = "stake"
fee_amount = 0
memo = ""

[ibcconfig]
    [[ibcconfig.chains]]
    chainid = "gaia"
    grpc = "http:/localhost:9090"
    rpc = "http://localhost:26657"
    dstaccount = "cosmos18zh6zd2kwtekjeg0ns5xvn2x28hgj8n6gxhe8c"
    tokendenom  = "uatom"
    accounthd ="44'/118'/0'/0/0"
    accountaddrprefix="cosmos"
    [[ibcconfig.chains]]
    chainid = "band"
    grpc = "http:/localhost:9595"
    rpc = "http://localhost:26557"
    dstaccount = "band1dn94fk7ul6gj7dprdnw7ufvepmkwaun7tn8n4t"
    tokendenom  = "uband"
    accounthd ="m/44'/494'/0'/0/0"
    accountaddrprefix="band"
    [[ibcconfig.chains]]
    chainid = "terra"
    grpc = "http:/localhost:9292"
    rpc = "http://localhost:26257"
    dstaccount = "terra17pdf2zxfcuclavl7874tjwuk89aga06h8uqzxz"
    tokendenom  = "uluna"
    accounthd ="m/44'/330'/0'/0/0"
    accountaddrprefix="terra"
    [[ibcconfig.chains]]
    chainid = "osmo"
    grpc = "http:/localhost:9494"
    rpc = "http://localhost:26457"
    dstaccount = "osmo18zh6zd2kwtekjeg0ns5xvn2x28hgj8n6qayf32"
    tokendenom  = "uosmo"
    accounthd ="44'/118'/0'/0/0"
    accountaddrprefix="osmo"
    [[ibcconfig.chains]]
    chainid = "sentinelhub"
    grpc = "http:/localhost:9191"
    rpc = "http://localhost:26157"
    dstaccount = "sent18zh6zd2kwtekjeg0ns5xvn2x28hgj8n6napqrh"
    tokendenom  = "udvpn"
    accounthd ="44'/118'/0'/0/0"
    accountaddrprefix="sent"
    [[ibcconfig.chains]]
    chainid = "cro"
    grpc = "http:/localhost:9999"
    rpc = "http://localhost:26957"
    dstaccount = "cro1jhn9z0q0t3872kw7hkuz40yx5rj5hmhrf6u0pp"
    tokendenom  = "ucro"
    accounthd ="m/44'/394'/0'/0/0"
    accountaddrprefix="cro"
    [[ibcconfig.chains]]
    chainid = "regen"
    grpc = "http:/localhost:9797"
    rpc = "http://localhost:26757"
    dstaccount = "regen18zh6zd2kwtekjeg0ns5xvn2x28hgj8n6hyu93u"
    tokendenom  = "uregen"
    accounthd ="44'/118'/0'/0/0"
    accountaddrprefix="regen"
    [[ibcconfig.chains]]
    chainid = "iris"
    grpc = "http:/localhost:9393"
    rpc = "http://localhost:26357"
    dstaccount = "iaa18zh6zd2kwtekjeg0ns5xvn2x28hgj8n6ayhg9f"
    tokendenom  = "uiris"
    accounthd ="44'/118'/0'/0/0"
    accountaddrprefix="iaa"
    [[ibcconfig.chains]]
    chainid = "akash"
    grpc = "http:/localhost:9898"
    rpc = "http://localhost:26957"
    dstaccount = "akash18zh6zd2kwtekjeg0ns5xvn2x28hgj8n69a677z"
    tokendenom  = "uakt"
    accounthd ="44'/118'/0'/0/0"
    accountaddrprefix="akash"
    [[ibcconfig.chains]]
    chainid = "persistenceCore"
    grpc = "http:/localhost:3030"
    rpc = "http://localhost:36657"
    dstaccount = "persistence1qj57lazgwmmnnnthfajl4r0xfsrz02eknn9gz6"
    tokendenom  = "uxprt"
    accounthd ="m/44'/750'/0'/0/0"
    accountaddrprefix="persistence"

